version: 0.1 
 
phases:
  install:
    commands:
      - echo Insatlling NPM Packages and wget Enviorment File
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://wdp-front
artifacts:
  discard-paths: yes

  